//Guestbook
export const CREATE_GUESTBOOK = "CREATE_GUESTBOOK";
export const DELETE_GUESTBOOK = "DELETE_GUESTBOOK";
export const LOAD_GUESTBOOK = "LOAD_GUESTBOOK";
export const COUNT_GUESTBOOK = "COUNT_GUESTBOOK";

//Notice
export const LOAD_NOTICE = "LOAD_NOTICE";
export const LOAD_ONE_NOTICE = "LOAD_ONE_NOTICE";
export const CREATE_NOTICE = "CREATE_NOTICE";
export const ADD_LIKE = "ADD_LIKE";
export const CREATE_NOTICE_COMMENT = "CREATE_NOTICE_COMMENT";
export const DELETE_NOTICE_COMMENT = "DELETE_NOTICE_COMMENT";
export const DELETE_NOTICE = "DELETE_NOTICE";
export const SEARCH_NOTICE = "SEARCH_NOTICE";
export const DELETE_LIKE = "DELETE_LIKE";
export const COUNT_NOTICE = "COUNT_NOTICE";

//Study
export const CREATE_STUDY = "CREATE_STUDY";
export const LOAD_STUDY = "LOAD_STUDY";
export const DELETE_STUDY = "DELETE_STUDY";
export const LOAD_ONE_STUDY = "LOAD_ONE_STUDY";
export const CREATE_STUDY_COMMENT = "CREATE_STUDY_COMMENT";
export const DELETE_STUDY_COMMENT = "DELETE_STUDY_COMMENT";

//USER
export const AUTH_USER = "AUTH_USER";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const DELETE_USER = "DELETE_USER";
