//ERROR
export const SERVER_ERROR = "SERVER_ERROR";
export const BCRYPT_ERROR = "BCRYPT_ERROR";
//Guestbook
export const CREATE_GUESTBOOK = "CREATE_GUESTBOOK";
export const DELETE_GUESTBOOK = "DELETE_GUESTBOOK";
export const LOAD_GUESTBOOK = "LOAD_GUESTBOOK";
export const COUNT_GUESTBOOK = "COUNT_GUESTBOOK";

//Notice
export const LOAD_NOTICE = "LOAD_NOTICE";
export const LOAD_ONE_NOTICE = "LOAD_ONE_NOTICE";
export const CREATE_NOTICE = "CREATE_NOTICE";
export const DELETE_NOTICE = "DELETE_NOTICE";
export const SEARCH_NOTICE = "SEARCH_NOTICE";
export const ADD_LIKE = "ADD_LIKE";
export const DELETE_LIKE = "DELETE_LIKE";
export const CREATE_NOTICE_COMMENT = "CREATE_NOTICE_COMMENT";
export const DELETE_NOTICE_COMMENT = "DELETE_NOTICE_COMMENT";
export const COUNT_NOTICE = "COUNT_NOTICE";

//Study
export const CREATE_STUDY = "CREATE_STUDY";
export const LOAD_STUDY = "LOAD_STUDY";
export const DELETE_STUDY = "DELETE_STUDY";
export const LOAD_ONE_STUDY = "LOAD_ONE_STUDY";
export const UPDATE_STUDY_TEXT = "UPDATE_STUDY_TEXT";
export const CREATE_STUDY_COMMENT = "CREATE_STUDY_COMMENT";
export const DELETE_STUDY_COMMENT = "DELETE_STUDY_COMMENT";
export const LOAD_STUDY_COMMENT = "LOAD_STUDY_COMMENT";
export const LOAD_MAIN_STUDY = "LOAD_MAIN_STUDY";
export const LOAD_ONE_STUDY_ERROR = "LOAD_ONE_STUDY_ERROR";
export const LOAD_STUDY_COMMENT_ERROR = "LOAD_STUDY_COMMENT_ERROR";
export const CREATE_STUDY_ERROR = "CREATE_STUDY_ERROR";
export const LOAD_STUDY_ERROR = "LOAD_STUDY_ERROR";
export const LOAD_MAIN_STUDY_ERROR = "LOAD_MAIN_STUDY_ERROR";
export const UPDATE_STUDY_TEXT_ERROR = "UPDATE_STUDY_TEXT_ERROR";
export const DELETE_STUDY_ERROR = "DELETE_STUDY_ERROR";
export const CREATE_STUDY_COMMENT_ERROR = "CREATE_STUDY_COMMENT_ERROR";
export const DELETE_STUDY_COMMENT_ERROR = "DELETE_STUDY_COMMENT_ERROR";

//USER
export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const AUTH_USER = "AUTH_USER";
export const AUTH_ERROR = "AUTH_ERROR";
export const UPDATE_NICK = "UPDATE_NICK";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const DELETE_USER = "DELETE_USER";
export const UPDATE_IMAGE = "UPDATE_IMAGE";
export const DELETE_IMAGE_ERROR = "DELETE_IMAGE_ERROR";
export const DELETE_IMAGE = "DELETE_IMAGE";
export const UPDATE_MOTTO_ERROR = "UPDATE_MOTTO_ERROR";
export const UPDATE_MOTTO = "UPDATE_MOTTO";
export const FIND_PASSWORD = "FIND_PASSWORD";
export const NOT_FIND_PASSWORD = "NOT_FIND_PASSWORD";
export const NEW_PASSWORD = "NEW_PASSWORD";
export const NEW_PASSWORD_FAIL = "NEW_PASSWORD_FAIL";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const UPDATE_NICK_ERROR = "UPDATE_NICK_ERROR";
export const UPDATE_PASSWORD_ERROR = "UPDATE_PASSWORD_ERROR";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";
export const UPDATE_IMAGE_ERROR = "UPDATE_IMAGE_ERROR";
