//Guestbook
export const CREATE_GUESTBOOK = 'CREATE_GUESTBOOK';
export const DELETE_GUESTBOOK = 'DELETE_GUESTBOOK';
export const LOAD_GUESTBOOK = 'LOAD_GUESTBOOK';
export const GUESTBOOK_PAGENATION_COUNT = 'GUESTBOOK_PAGENATION_COUNT';
export const GUESTBOOK_ERROR = 'GUESTBOOK_ERROR'


//Notice
export const LOAD_NOTICE = 'LOAD_NOTICE';
export const LOAD_ONE_NOTICE = 'LOAD_ONE_NOTICE';
export const LOAD_COMMENT = 'LOAD_COMMENT';
export const CREATE_NOTICE = 'CREATE_NOTICE';
export const DELETE_NOTICE = 'DELETE_NOTICE';
export const UPDATE_NOTICE = 'UPDATE_NOTICE';
export const SEARCH_NOTICE = 'SEARCH_NOTICE';
export const LOAD_LIKE = 'LOAD_LIKE';
export const ADD_LIKE = 'ADD_LIKE';
export const DELETE_LIKE = 'DELETE_LIKE';
export const CREATE_NOTICE_COMMENT = 'CREATE_NOTICE_COMMENT';
export const DELETE_NOTICE_COMMENT = 'DELETE_NOTICE_COMMENT';
export const NOTICE_ERROR = 'NOTICE_ERROR';
export const LIKE_ERROR = 'LIKE_ERROR';



//Study
export const CREATE_STUDY = 'CREATE_STUDY';
export const LOAD_STUDY = 'LOAD_STUDY';
export const DELETE_STUDY = 'DELETE_STUDY';
export const LOAD_ONE_STUDY = 'LOAD_ONE_STUDY';
export const UPDATE_STUDY_TEXT ='UPDATE_STUDY_TEXT';
export const STUDY_ERROR = 'STUDY_ERROR';
export const CREATE_STUDY_COMMENT = 'CREATE_STUDY_COMMENT';
export const DELETE_STUDY_COMMENT = 'DELETE_STUDY_COMMENT';
export const LOAD_STUDY_COMMENT = 'LOAD_STUDY_COMMENT';
export const STUDY_COMMENT_ERROR= 'STUDY_COMMENT_ERROR';


//USER
export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const UPDATE_ERROR = 'UPDATE_ERROR';
export const UPDATE_NICK = 'UPDATE_NICK';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const DELETE_ERROR ='DELETE_ERROR';
export const DELETE_USER = 'DELETE_USER';
export const UPDATE_IMAGE = 'UPDATE_IMAGE';
export const DELETE_IMAGE_ERROR = 'DELETE_IMAGE_ERROR';
export const DELETE_IMAGE = 'DELETE_IMAGE'
export const UPDATE_MOTTO_ERROR = 'UPDATE_MOTTO_ERROR';
export const UPDATE_MOTTO = 'UPDATE_MOTTO';
