//Guestbook
export const CREATE_GUESTBOOK = 'CREATE_GUESTBOOK';
export const DELETE_GUESTBOOK = 'DELETE_GUESTBOOK';
export const LOAD_GUESTBOOK = 'LOAD_GUESTBOOK';
export const GUESTBOOK_PAGENATION_COUNT = 'GUESTBOOK_PAGENATION_COUNT';
